"""Build an inventory of NFL 2K5's native ESPN presentation triggers.

The runtime already logs the presentation script interpreter, card builder,
popup system, and lineup ticker.  This tool correlates those records across
logs/*.log and writes a stable Markdown/CSV report.  It does not infer a
replacement graphic from timing alone; unknown card kinds stay unknown until
a screenshot or the native text identifies them.
"""
from __future__ import annotations

import argparse
import csv
import re
import subprocess
from collections import Counter, defaultdict
from pathlib import Path

CARD = re.compile(r"\[CARD\] ctx=([0-9A-F]+) kind=(\d+)")
POP = re.compile(r"\[POPUPOP\] show obj=([0-9A-F]+) slot=(-?\d+) t=([^ ]+) '([^']*)' '([^']*)'")
SCRIPT = re.compile(r"\[SCRIPT\] ctx=([0-9A-F]+) op=\s*(\d+) (start|poll)\s+type=(\d+) start=([0-9A-F]+) poll=([0-9A-F]+)")
LINEUP = re.compile(r"\[PRES\] lineup (offense|defense):")


def clean(s: str) -> str:
    return s.strip() or "(blank title)"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--logs", default="logs")
    ap.add_argument("--out", default="docs/ESPN-GRAPHICS-TRIGGER-MAP.md")
    ap.add_argument("--csv", default="logs/espn-card-triggers.csv")
    args = ap.parse_args()
    root = Path(__file__).resolve().parents[1]
    log_dir = root / args.logs

    card_pairs: Counter[tuple[int, str, str]] = Counter()
    card_files: defaultdict[int, set[str]] = defaultdict(set)
    popup_titles: Counter[tuple[int, str, str]] = Counter()
    script_ops: Counter[tuple[int, int, str, str]] = Counter()
    lineups: Counter[str] = Counter()

    # A development tree may contain gigabytes of unrelated renderer/audio
    # logs. Let ripgrep select only files containing presentation markers.
    marker = r"\[CARD\]|\[POPUPOP\]|\[SCRIPT\]|\[PRES\] lineup"
    cached_list = log_dir / "card-log-files.txt"
    if cached_list.exists():
        paths = [(root / p.strip()).resolve() for p in cached_list.read_text().splitlines() if p.strip()]
    else:
        found = subprocess.run(
            ["rg", "-l", marker, str(log_dir), "-g", "*.log"],
            text=True, capture_output=True, check=False,
        )
        paths = [Path(p) for p in found.stdout.splitlines() if p.strip()]
    for path in sorted(paths):
        try:
            lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        except OSError:
            continue
        pending_card: tuple[int, int] | None = None
        last_script: tuple[int, int, str, str] | None = None
        for lineno, line in enumerate(lines, 1):
            if m := SCRIPT.search(line):
                key = (int(m[2]), int(m[4]), m[5], m[6])
                script_ops[key] += 1
                if m[3] == "start":
                    last_script = key
            if m := CARD.search(line):
                kind = int(m[2])
                pending_card = (kind, lineno)
                card_files[kind].add(path.name)
            if m := POP.search(line):
                slot, timeout, title, message = int(m[2]), m[3], clean(m[4]), clean(m[5])
                popup_titles[(slot, title, message)] += 1
                if slot == 1 and pending_card and lineno - pending_card[1] <= 12:
                    kind = pending_card[0]
                    op = str(last_script[0]) if last_script else "?"
                    card_pairs[(kind, title, op)] += 1
                    pending_card = None
            if m := LINEUP.search(line):
                lineups[m[1]] += 1

    out_csv = root / args.csv
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    with out_csv.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["card_kind", "native_title", "nearest_script_opcode", "observations"])
        for (kind, title, op), n in sorted(card_pairs.items()):
            w.writerow([kind, title, op, n])

    known = {
        133: "Native player/stat card command (confirmed hook in sub_002604D0)",
    }
    md: list[str] = [
        "# ESPN graphics trigger map",
        "",
        "Generated by `tools/analyze-presentation-triggers.py` from runtime logs. "
        "Counts are observations, not guesses about graphic meaning.",
        "",
        "To collect a focused trace without enabling every verbose runtime diagnostic, "
        "launch with `NFL2K5_PRESENTATION_TRACE=1`. After the session, run this tool again.",
        "",
        "## Hooked trigger families",
        "",
        "| Native family | Runtime hook | Data captured |",
        "|---|---|---|",
        "| Presentation script | `DIAG_SCRIPTOP` in `sub_000DBC10` | opcode, command type, start/poll handlers, context |",
        "| ESPN player/stat cards | `PLAYERCARD_PROBE` in `sub_002604D0` | card kind, roster pointers, native popup title |",
        "| Generic ESPN popups | `DIAG_POPUPSHOW` in `sub_0008ACF0` | slot, timeout, title, message, callback |",
        "| Starting lineup ticker | `LINEUP_TICKER` in `sub_000FFBA0` | offense/defense and eleven roster records |",
        "| Scorebug visibility/layout | hooks in `sub_000FC200` / `sub_000FCE70` | native visibility and live scorebug state |",
        "| Period boundary | broadcast state at `0x00E602C4` | quarter transition, halftime, overtime, final |",
        "",
        "## Observed ESPN card kinds",
        "",
        "| Kind | Native title seen immediately after trigger | Nearest script op | Count | Logs |",
        "|---:|---|---:|---:|---:|",
    ]
    all_kinds = sorted(set(card_files) | {k for k, _, _ in card_pairs})
    for kind in all_kinds:
        pairs = [(title, op, n) for (k, title, op), n in card_pairs.items() if k == kind]
        if not pairs:
            md.append(f"| {kind} | unknown / no title captured | ? | 0 | {len(card_files[kind])} |")
        else:
            summary = "; ".join(f"{title} ({n})" for title, _, n in sorted(pairs, key=lambda x: (-x[2], x[0])))
            ops = ", ".join(sorted({op for _, op, _ in pairs}))
            md.append(f"| {kind} | {summary} | {ops} | {sum(n for _, _, n in pairs)} | {len(card_files[kind])} |")

    md += [
        "",
        "## Native popup titles",
        "",
        "These are direct title strings from the game. Slot `1` is the ESPN "
        "broadcast-card layer; slot `-1` contains gameplay notices such as penalties and injuries.",
        "",
        "| Slot | Title | Message/example | Count |",
        "|---:|---|---|---:|",
    ]
    for (slot, title, message), n in sorted(popup_titles.items(), key=lambda x: (-x[1], x[0])):
        if n < 2 and title == "(blank title)":
            continue
        md.append(f"| {slot} | {title.replace('|', '/')} | {message.replace('|', '/')} | {n} |")

    md += [
        "",
        "## Presentation script opcodes observed",
        "",
        "| Opcode | Type | Start handler | Poll handler | Starts/polls observed | Meaning |",
        "|---:|---:|---:|---:|---:|---|",
    ]
    for (op, typ, start, poll), n in sorted(script_ops.items()):
        md.append(f"| {op} | {typ} | `{start}` | `{poll}` | {n} | {known.get(op, 'unclassified')} |")

    md += [
        "",
        "## Replacement rule",
        "",
        "A custom broadcast package should replace an ESPN graphic only after its exact native "
        "trigger is identified. Live GameCast/roster values supply data; they do not trigger a graphic. "
        "For example, the FOX persistent QB insert stays inside FOX, while SNF player panels wait for "
        "the matching ESPN card or popup event.",
        "",
        f"Observed lineup triggers: offense {lineups['offense']}, defense {lineups['defense']}.",
        f"Machine-readable card table: `{Path(args.csv).as_posix()}`.",
    ]
    out_md = root / args.out
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_md.write_text("\n".join(md) + "\n", encoding="utf-8")
    print(out_md)
    print(out_csv)


if __name__ == "__main__":
    main()
